version: '3.8'

services:
  django_ninja:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=dev

  database:
    image: postgres:16
    container_name: postgres_db
    restart: always
    volumes:
      - "C:/Program Files/PostgreSQL/16/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: local_db
      POSTGRES_PORT: 5433
      POSTGRES_HOST: localhost
volumes:
  postgres_data:
