
version: '3.8'

services:
  django_ninja:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - path: ./.env
        required: true
    environment:
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      ALLOWED_HOST: ${DJANGO_ALLOWED_HOST}
      DATABASE_HOST: host.docker.internal
