# Generated by Django 5.1.7 on 2025-03-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoninja', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(auto_now=True),
        ),
    ]
